Added RPC and a message type
octoposprime/op-be-shared pull request #29
Opened 2024-06-03 14:38 UTC by Smnrgcl

Closes #21 

Added **CheckUserPassword RPC** and **UserWithPassword message** type to enable password validation in user management. Enhances security and usability by allowing clients to verify user credentials directly.

2024-06-04 09:24 UTC, Feyzanrs approved these changes, later dismissed

2024-07-11 12:48 UTC, Sddilora requested changes

2024-07-11 12:48 UTC, Sddilora commented on pkg/proto/model/user.proto
> +    rpc CheckUserPassword(UserWithPassword) returns (User) {}
there is an indent problem in here

2024-07-12 10:44 UTC, Feyzanrs submitted a review, later dismissed

2024-07-12 17:52 UTC, merged